server:
  port: 8183

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=WeSign;trustServerCertificate=true;encrypt=false
    username: sa
    password: 1234
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
    show-sql: true

keycloak:
  server-url: http://localhost:8080
  realm: master
  client-id: admin-cli
  username: admin
  password: admin